# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'AdUnitDemo' do
  use_frameworks!
      pod 'Firebase/Core'
      pod 'Firebase/AdMob'
      pod 'GoogleTagManager', '~> 3.15.0'
end
